/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.1.0/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    kotlin("jvm") version "2.2.0"

    // Apply the java-library plugin for API and implementation separation.
    `java-library`
    
    // Kotlin serialization plugin
    kotlin("plugin.serialization") version "2.2.0"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
    
    // AWS SDK repository
    maven {
        url = uri("https://aws.oss.sonatype.org/content/repositories/snapshots/")
    }
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation("org.junit.jupiter:junit-jupiter:5.14.2")

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
    
    // MockK for mocking in tests
    testImplementation("io.mockk:mockk:1.13.13")
    
    // Kotlin test utilities
    testImplementation("org.jetbrains.kotlin:kotlin-test:2.2.0")

    // Guava/Gson
    implementation("com.google.guava:guava:33.5.0-jre")
    
    // Jackson dependencies for JSON processing
    implementation("com.fasterxml.jackson.core:jackson-core:2.18.2")
    implementation("com.fasterxml.jackson.core:jackson-databind:2.18.2")
    implementation("com.fasterxml.jackson.module:jackson-module-kotlin:2.18.2")
    
    // JSON Schema generation
    implementation("com.github.victools:jsonschema-generator:4.36.0")
    implementation("com.github.victools:jsonschema-module-javax-validation:4.36.0")
    implementation("javax.validation:validation-api:2.0.1.Final")

    // JSON Schema validation
    implementation("com.networknt:json-schema-validator:1.5.3")
    
    // Vavr for functional programming
    implementation("io.vavr:vavr-kotlin:0.10.2")
    
    // Kotlinx Serialization
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.7.3")
    
    // AWS SDK for Bedrock Runtime
    implementation("aws.sdk.kotlin:bedrockruntime:1.6.68")
    
    // Model Context Protocol Kotlin SDK
    implementation("io.modelcontextprotocol:kotlin-sdk:0.4.0")
    
    // SLF4J for logging
    implementation("org.slf4j:slf4j-api:2.0.16")
    implementation("ch.qos.logback:logback-classic:1.5.12")
    
    // Kotlin reflection
    implementation("org.jetbrains.kotlin:kotlin-reflect:2.2.0")
    
    // Coroutines
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.9.0")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

tasks.register<JavaExec>("RunHackerNewsAgenticFunction") {
    mainClass.set("com.amazon.agentio.example.hackernews.RunnerKt")
    classpath = sourceSets["main"].runtimeClasspath
    debug = false
    debugOptions {
        server = true
        suspend = true
        host = "localhost"
        port = 5010
    }
    args = listOf(
        "${project.projectDir}/src/main/kotlin/com/amazon/agentio/example/hackernews/server/server_hacker_news.sh",
    )
}

tasks.register<JavaExec>("RunAdaptiveExperiment") {
    description = "Run the Adaptive CMM experiment (Needle-in-a-Haystack / Multi-Needle)"
    group = "experiment"
    mainClass.set("com.amazon.agentio.experiment.adaptive.RunnerKt")
    classpath = sourceSets["main"].runtimeClasspath
}
